import{a as S,S as q,i as p}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function m(r,o){const s={q:r,key:"52578833-1380a7e48419fcc1cc100434d",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o},a=await S.get("https://pixabay.com/api/",{params:s});return{hits:a.data.hits,totalHits:a.data.totalHits}}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".loader-btn"),g=new q(".gallery a",{captionsData:"alt",captionDelay:150});function b(r){return r.map(({webformatURL:o,largeImageURL:s,tags:a,likes:e,views:t,comments:i,downloads:M})=>`
<li class="photo-card">
  <a href="${s}" class="gallery-link" aria-label="${a}">
    <img src="${o}" alt="${a}" loading="lazy" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${e}</span></p>
    <p class="info-item"><b>Views</b><span>${t}</span></p>
    <p class="info-item"><b>Comments</b><span>${i}</span></p>
    <p class="info-item"><b>Downloads</b><span>${M}</span></p>
  </div>
</li>`).join("")}function P(){f.innerHTML=""}function L(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}function v(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const w={form:document.querySelector(".form"),loadMoreBtn:document.querySelector(".loader-btn")},$=15;let d,n,u;l();w.form.addEventListener("submit",async r=>{r.preventDefault(),d=new FormData(r.target).get("search-text").trim(),n=1,P(),l(),L();try{const s=await m(d,n);if(c(),s.hits.length===0){p.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const a=b(s.hits);f.innerHTML=a,g.refresh(),u=Math.ceil(s.totalHits/$),n<u&&v()}catch{err,console.error(err),c()}r.target.reset()});w.loadMoreBtn.addEventListener("click",async()=>{n+=1,L(),l();try{const r=await m(d,n);c();const o=b(r.hits);f.insertAdjacentHTML("beforeend",o),g.refresh(),n>=u?(l(),p.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch(r){console.error(r),c()}});
//# sourceMappingURL=index.js.map
