import{a as q,S as M,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();async function h(e,s){const t={q:e,key:"52578833-1380a7e48419fcc1cc100434d",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s},i=await q.get("https://pixabay.com/api/",{params:t});return{hits:i.data.hits,totalHits:i.data.totalHits}}const u=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".loader-btn"),P=new M(".gallery a",{captionsData:"alt",captionDelay:150});function g(){try{P.refresh()}catch(e){console.warn("Lightbox refresh failed:",e)}}function y(e){return e.map(({webformatURL:s,largeImageURL:t,tags:i,likes:r,views:o,comments:c,downloads:S})=>`
<li class="photo-card">
  <a href="${t}" class="gallery-link" aria-label="${i}">
    <img src="${s}" alt="${i}" loading="lazy" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${r}</span></p>
    <p class="info-item"><b>Views</b><span>${o}</span></p>
    <p class="info-item"><b>Comments</b><span>${c}</span></p>
    <p class="info-item"><b>Downloads</b><span>${S}</span></p>
  </div>
</li>`).join("")}function B(){u.innerHTML=""}function b(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function w(){m.classList.remove("hidden")}function d(){m.classList.add("hidden")}const v={form:document.querySelector(".form"),loadMoreBtn:document.querySelector(".loader-btn")},R=15;let l="",n,f=0;d();v.form.addEventListener("submit",async e=>{if(e.preventDefault(),l=new FormData(e.target).get("search-text").trim(),!l){a.warning({title:"",message:"Please enter a search query.",position:"topRight"}),e.target.reset();return}n=1,B(),d(),b();try{const t=await h(l,n);if(!t.hits||t.hits.length===0){a.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const i=y(t.hits);u.innerHTML=i,g(),f=Math.ceil(t.totalHits/R),n<f?w():(a.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d())}catch(t){console.error("Search error:",t),a.error({title:"",message:"An error occurred while fetching images. Please try again.",position:"topRight"})}finally{L()}e.target.reset()});v.loadMoreBtn.addEventListener("click",async()=>{if(l){n+=1,b(),d();try{const e=await h(l,n);if(!e.hits||e.hits.length===0){a.info({title:"",message:"No more images found.",position:"topRight"});return}const s=y(e.hits);u.insertAdjacentHTML("beforeend",s),g();try{const t=u.firstElementChild;if(t){const{height:i}=t.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch(t){console.warn("Scroll adjustment failed:",t)}n>=f?(d(),a.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(e){console.error("Load more error:",e),a.error({title:"",message:"An error occurred while loading more images.",position:"topRight"})}finally{L()}}});
//# sourceMappingURL=index.js.map
