import{a as q,S as E,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const R="https://pixabay.com/api/",M="52578833-1380a7e48419fcc1cc100434d",$=15;async function f(r,t=1){const s={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:$,page:t};return(await q.get(R,{params:s})).data}const d=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".loader-btn"),B=new E(".gallery a",{captionsData:"alt",captionDelay:150});function y(r,t={append:!1}){const s=r.map(({webformatURL:i,largeImageURL:e,tags:o,likes:c,views:v,comments:P,downloads:S})=>`
<li class="photo-card">
  <a href="${e}">
    <img src="${i}" alt="${o}" loading="lazy" />
  </a>
  <div class="info">
    <p><b>Likes</b> ${c}</p>
    <p><b>Views</b> ${v}</p>
    <p><b>Comments</b> ${P}</p>
    <p><b>Downloads</b> ${S}</p>
  </div>
</li>`).join("");t.append?d.insertAdjacentHTML("beforeend",s):d.innerHTML=s,B.refresh()}function A(){d.innerHTML=""}function b(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function w(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function H(){const r=d.querySelector(".photo-card");return r?r.getBoundingClientRect().height:0}const h=document.querySelector(".form"),O=document.querySelector(".loader-btn"),_=15;let l="",a=1,u=0;p();h.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!l){n.warning({message:"Please enter a search query.",position:"topRight"});return}a=1,A(),p(),b();try{const t=await f(l,a);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}y(t.hits),u=Math.ceil(t.totalHits/_),a>=u?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}h.reset()});O.addEventListener("click",async()=>{a+=1,b(),p();try{const r=await f(l,a);y(r.hits,{append:!0});const t=H();window.scrollBy({top:t*2,behavior:"smooth"}),a>=u?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w()}catch{n.error({message:"Error loading more images.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
